import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

import { useEffect, useState } from "react";
import { apiNoToken } from "@/config/api";

export default function Home() {
  const [tabs, setTabs] = useState([]);

  useEffect(() => {
    async function fetchTabs() {
      try {
        const res = await apiNoToken.get("/tab/all-tabs");
        setTabs(res.data);
      } catch (e) {
        console.log(e);
      }
    }
    fetchTabs();
  }, []);

  return (
    <>
      <Head>
        <title>Página Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Testando</h1>
        <Image
          src="/images/perfil.jpg"
          alt="Vercel Logo"
          width={100}
          height={100}
          priority
        />
        {tabs?.map((e) => {
          return (
            <div key={e._id} className="bg-slate-400 mx-3 my-3 w-96 rounded-md">
              {" "}
              {e.title}
            </div>
          );
        })}
      </main>
    </>
  );
}
