import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import axios from "axios";
import { useEffect, useState } from "react";

export default function Home() {
  const [tabs, setTabs] = useState([]);

  useEffect(() => {
    async function fetchTabs() {
      try {
        const res = await axios.get("http://localhost:4000/tab/all-tabs");
        setTabs(res.data);
      } catch (e) {
        console.log(e);
      }
    }
    fetchTabs();
  }, []);

  console.log(tabs);
  return (
    <>
      <Head>
        <title>Página Principal</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1> Testando</h1>
        <Image
          src="/images/perfil.jpg"
          alt="Vercel Logo"
          width={100}
          height={100}
          priority
        />
        <Link href="/blog/1"> Post</Link>
        {tabs?.map((e) => {
          return <div key={e._id}> {e.title}</div>;
        })}
      </main>
    </>
  );
}
